### ISSUE TITLE
When will version 2.1.0 be released?

### ISSUE THREAD

**Issue by richmain-sas** [blackducksoftware/black-duck-radar#12]
The Black Duck August update email that was sent out this week mentions the following:

> - **Black Duck Radar 2.1.0.** Supports checking against components in a customer’s Artifactory instance for the following repositories: Composer, Maven, NuGet, NPM, PyPI, RubyGems. Also updates UI messaging to indicate when a package isn’t found.

However, I can't find a 2.1.0 release here on GitHub or in the Chrome web store.

What is the plan for releasing Black Duck Radar 2.1.0?

**Comment by psantos1113** [comment]
2.1.0 was released September 17th 2019.  Resolving this issue to prepare for another release.
