### ISSUE TITLE
Black Duck radar on npmjs.org is not working

### ISSUE THREAD

**Issue by Tearion** [blackducksoftware/black-duck-radar#13]
I've just installed black duck radar and its working on nuget.org and mvncentral, but not for npmjs.org (*.com). The Addon shows just the "Welcome to Radar" page with the green "Configured" icon.

Is there any fix planned?

Google Chrome
Version 76.0.3809.132 (Official Build) (64-bit)

Black Duck Radar
Version: 2.0.0

![image](https://user-images.githubusercontent.com/16781740/64595824-06e83a00-d3b3-11e9-9c30-4243d52f609e.png)

**Comment by psantos1113** [comment]
2.1.0 was released September 17th 2019.  Resolving this issue to prepare for another release.
