### ISSUE TITLE
Lack of visual feedback from the extension's black duck icon when viewing a nuget.org package not yet present in Black Duck Hub's database

### ISSUE THREAD

**Issue by NeilJustice** [blackducksoftware/black-duck-radar#3]
I'm seeing a lack of visual feedback from the extension's black duck icon when highlighting on nuget.org a version number not yet known by Black Duck Hub. When a NuGet package version number that Black Duck Hub does know about is highlighted on nuget.org, the extension's black duck icon shows visual feedback in the form of a green circle. It would be helpful to see perhaps a grey circle or question mark appear when the extension is not able to find a package or version number in Hub's database.

Example:
As of today, at https://www.nuget.org/packages/RestSharp/106.4.0, the extension does not show a green circle for RestSharp version 106.4.0 due to that version being released one day ago.
At https://www.nuget.org/packages/RestSharp/106.3.1, the extension shows a green circle for RestSharp version 106.3.1 due to that version being released 3 months ago.

Green circle when the extension finds a package and version number in Hub's database:
![image](https://user-images.githubusercontent.com/1912242/45777327-1d820800-bc1b-11e8-8a13-d225612383ab.png)

Zero visual feedback when the extension does not find a package and version number in Hub's database:
![image](https://user-images.githubusercontent.com/1912242/45777347-2a066080-bc1b-11e8-9ae5-787a8beaea77.png)

This Chrome extension has a lot of potential to save time by stopping the selection of GPL or security-unsafe packages at browser time instead of already-checked-in Black Duck Hub scan time. I look forward to testing and providing feedback on future versions of this extension.

**Comment by psantos1113** [comment]
We will display a question mark over the duck icon if the component information can be found on the page but no results are found in the blackduck server.
