### ISSUE TITLE
Login failures - Unchecked runtime.lastError: This function must be called during a user gesture 

### ISSUE THREAD

**Issue by richmain-sas** [blackducksoftware/black-duck-radar#5]
Multiple users at our company are reporting login failures with the Black Duck Radar chrome extension. I have reproduced the same failure.

The error reported by the extension is:

> Unchecked runtime.lastError: This function must be called during a user gesture 
> _generated_background_page.html:1

Note that the users can all log in to Black Duck via the UI. It's just the Black Duck radar login that is failing. We have multiple servers running 2018.12.01, and the same failure occurs regardless of the server we try to use from the extension.

**Comment by deathspiral** [comment]
Any update on this?  This is blocking multiple users.

**Comment by psantos1113** [comment]
There is work going on to address the issues with logging in for a new release of the extension.

**Comment by psantos1113** [comment]
I have run into similar issues when testing the api token functionality.  Now that API token functionality has been implemented this issue is resolved.

**Comment by richmain-sas** [comment]
I built and tested a local copy yesterday and can confirm that the authentication issues are fixed. Plus, I like the switch to using a token since that should help the authentication to persist.

When do you expect to officially release this new version? I can have some of my users install a local extension as a temporary workaround, but I'd prefer most of them to just be able to get the official extension.

**Comment by stavvy-akamen** [comment]
@richmain-sas we are going to submit this version of the extension to QA.  I am hoping no more than a few weeks, please ping us if we are taking too long!
